FROM ubuntu:16.04

ENV MANTA_URL https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.centos6_x86_64.tar.bz2
ENV MANTA_MD5 = "fccab1348fe182c63ad4f0e51d3dfcf0"

SHELL ["/bin/bash", "-c"]

RUN mkdir /downloads
RUN mkdir /manta
WORKDIR /downloads

RUN apt-get update -qq && \
	apt-get install -qq \
	bzip2 \
	gcc \
	g++ \
	make \
	python \
	zlib1g-dev \
	wget

RUN wget -nv $MANTA_URL && \
	tar -xjf manta-1.6.0.centos6_x86_64.tar.bz2 && \
	cd manta-1.6.0.centos6_x86_64 && \
	mv * /manta && \
	cd .. && \
	rm -rf manta-1.6.0.centos6_x86_64
